attendance_backend:
  build: .
  environment:
    - ATTENDANCEBACKEND_DATABASE_USERNAME=attendancebackend
    - ATTENDANCEBACKEND_DATABASE_PASSWORD=password
    - ATTENDANCEBACKEND_DATABASE=attendancebackend
    - ATTENDANCEBACKEND_DATABASE_HOST=postgres
    - ATTENDANCEBACKEND_DATABASE_PORT=5432
    - TRANSACT_URL=https://dcobroker.oit.duke.edu
    - IDMS_USER=eventsattendance
    - IDMS_PASSWORD=ieiA@GgtQVT+@*1KGRSDS3y+
    - RAILS_ENV=development
  ports:
    - "3001:3000"
  links:
      - postgres
postgres:
  image: "postgres"
  environment:
    - POSTGRES_USER=attendancebackend
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=attendancebackend
  ports:
    - "5432:5432"
  #   Set a volume some that database is not lost after shutting down the container.
  #   I used the name postgres-data but you can changed it to something else.
  volumes:
    - ./postgres-data:/var/lib/postgresql/data



